import { Cliente } from './cliente';

/*export const clientes: Cliente[] = [
  {
    id: 1,
    nombre: 'Angela',
    apellido: 'Peña',
    email: 'angelap@gmail.com',
    createAt: '2017-12-21',
    foto: '',
  },
  {
    id: 2,
    nombre: 'Mr. John',
    apellido: 'Doe',
    email: 'john.doe@gmail.com',
    createAt: '2017-11-11',
    foto: '',
  },
  {
    id: 3,
    nombre: 'Linus',
    apellido: 'Torvalds',
    email: 'linus.torvalds@gmail.com',
    createAt: '2017-11-12',
    foto: '',
  },
  {
    id: 4,
    nombre: 'Rasmus',
    apellido: 'Lerdorf',
    email: 'rasmus.lerdorf@gmail.com',
    createAt: '2017-11-13',
    foto: '',
  },
  {
    id: 5,
    nombre: 'Erich',
    apellido: 'Gamma',
    email: 'erich.gamma@gmail.com',
    createAt: '2017-11-14',
    foto: '',
  },
  {
    id: 6,
    nombre: 'Richard',
    apellido: 'Helm',
    email: 'richard.helm@gmail.com',
    createAt: '2017-11-15',
    foto: '',
  },
  {
    id: 7,
    nombre: 'Ralph',
    apellido: 'Johnson',
    email: 'ralph.johnson@gmail.com',
    createAt: '2017-11-16',
    foto: '',
  },
  {
    id: 8,
    nombre: 'Bombasto',
    apellido: 'Vlissides',
    email: 'bombasto.vlissides@gmail.com',
    createAt: '2017-11-17',
    foto: '',
  },
  {
    id: 9,
    nombre: 'Dr James',
    apellido: 'Gosling',
    email: 'james.gosling@gmail.com',
    createAt: '2017-11-18',
    foto: '',
  },
  {
    id: 10,
    nombre: 'Magma',
    apellido: 'Lee',
    email: 'magma.lee@gmail.com',
    createAt: '2017-11-19',
    foto: '',
  },
  {
    id: 11,
    nombre: 'Tornado',
    apellido: 'Roe',
    email: 'tornado.roe@gmail.com',
    createAt: '2017-11-20',
    foto: '',
  },
];*/
